### ISSUE TITLE
Expand benchmarks to include all tests

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#216]
We can simply change the testing implementation. See `examples/Utils.hs`.

**Comment by TotallyNotChase** [comment]
Not all the tests should be (or can be) benchmarked though, right? We should probably include a bench + test utility but also allow raw tests.

**Comment by L-as** [comment]
I think they all can be tested.

**Comment by srid** [comment]
Some tests evaluate more than one program. Might require some reorg here (for the `foo.bar.qux` hierarchical naming to make sense).

**Comment by L-as** [comment]
Well it's always either one or two. We could call the benches `"name:1"` and `"name:2"`.

**Comment by srid** [comment]
We can pull in the deterministic benchmarks _into_ tests via [golden testing](https://hackage.haskell.org/package/tasty-golden) (which also could cover the printTerm stuff, in principle). 

It also solves the problem of performance regressions being overlooked (because no one bothered to check the Hercules CI effects output for benchmark diff), because now the benchmark golden will have to be reviewed/updated by the PR author.

**Comment by srid** [comment]
This is only partly done; and will be completed as part of #302
