### ISSUE TITLE
Improve ergonomics of golden testing

### ISSUE THREAD

**Issue by srid** [Plutonomicon/plutarch#289]
> While not a blocking issue, I do wonder how we could make the testing API more ergonomic.

> I'll think about this outside this PR. Maybe some sort of MonadWriter that collects programs on the goal, and batches golden tests at the end ...

_Originally posted by @srid in https://github.com/Plutonomicon/plutarch/pull/276#discussion_r807401889_

**Comment by srid** [comment]
Resolved by #307

**Comment by TotallyNotChase** [comment]
it might be better to link these "already resolved in staging" with the `staging -> master` PR, so that they get closed once that PR gets merged.

**Comment by srid** [comment]
@TotallyNotChase Worth opening an issue to discuss the meta issue? cf. https://github.com/Plutonomicon/plutarch/issues/312#issuecomment-1047010445

I believe the workflow we used for 1.1 release was the other way: PRs to master, and then master gets merged to staging.

**Comment by TotallyNotChase** [comment]
Also, I have nothing against any particular workflow btw - that's upto others to decide (but I'm fine with the current one). However, since we'll be closing a bunch of issues during the release cycle - it's worth tagging them in the `staging -> master` PR whenever a relevant PR gets merged into `staging`. Manually closing one by one like this is pain and loses context.
