### ISSUE TITLE
Make invariants for `PMap` and `PValue` explicit

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#344]
- Map entries should be sorted.
- Value must not contain entries of zero amount.

**Comment by L-as** [comment]
Related:
- #303
- #326

**Comment by blamario** [comment]
No function in [PlutusTx.AssocMap](https://playground.plutus.iohkdev.io/doc/haddock/plutus-tx/html/src/PlutusTx.AssocMap.html#toList) enforces ordering nor requires the `Ord k` constraint. They also seem very inefficient for unrelated reasons, but that's beside the point. The point is we have to work with `Value`s as we get them, which is unsorted, not as we wish they were in Plutus.

**Comment by L-as** [comment]
I'm not sure what you mean? If you mean putting `Value` into datums, then that would be covered by a `PTryFrom` implementation.

**Comment by blamario** [comment]
No, I meant actual values in output UTxOs in the `ScriptContext` given to the validator. Keep in mind that the `ScriptContext` can be constructed by multiple testing libraries as well as the actual Cardano node. Do we trust all of them to normalize the script context? Just today there's this issue reported in Slack https://mlabs-corp.slack.com/archives/C02QQHLFB6Y/p1648459396901379 where `plutus-simple-model` doesn't filter out the zero token quantities. Speaking of which, the PlutusTx implementation of equality [doesn't expect](https://playground.plutus.iohkdev.io/doc/haddock/plutus-ledger-api/html/src/Plutus.V1.Ledger.Value.html#eq) the zeroes to be filtered out.

Furthermore, suppose in some future ~release~commit of `cardano-node` or wherever this logic is, the values in `ScriptContext` UTxOs are *not* properly normalized, either through oversight or by design. A PlutusTx-compiled validator won't be affected, Plutarch will be. I wouldn't expect IOHK to accept the blame for creating a new vulnerability in the Plutarch-compiled validator scripts that would have been *already present* on-chain. Their reference implementation is safe after all.

This situation sucks from the performance point of view, but unless we have a written-down guarantee that UTxO values are always going to be normalized, the only sane way to ensure Plutarch's forward-compatible safety on-chain is to replicate the behaviour of PlutusTx. Not necessarily the implementation, mind you. The linked PlutusTx equality comparison starts by converting the two maps into a list of `These`.

**Comment by blamario** [comment]
BTW the  `instance Eq Map` (as opposed to `Value`) doesn't even sort:
```
newtype Map k v = Map { unMap :: [(k, v)] }
    deriving stock (Generic, Haskell.Eq, Haskell.Show)
```
https://playground.plutus.iohkdev.io/doc/haddock/plutus-tx/html/src/PlutusTx.AssocMap.html#Map

We may want to have two `Map` types, one compatible with the sucky `PlutusTx` one and the other with proper guarantees. And if I were allowed only one, I'd go for the proper one but with strong warnings in the documentation that it differs from the standard `PlutusTx.Map`. It's the users' choice to use it in their datums and elsewhere if they want it, as opposed to `Value` which they can't control.

**Comment by blamario** [comment]
I've proceeded with PR #396 on the assumption we don't expect `Value` to be normalized. One reason for that is the discouraging comments from IOHK, linked above. The other is that I expect a large majority of on-chain values in practice to contain only a couple of tokens. In this situation the dumbest algorithm can be the fastest.

**Comment by blamario** [comment]
The adopted solution in PR #296 ended up adding phantom type parameters to `PValue` to track the value's normalization. This allows users to be explicit about their assumptions. Until proven otherwise, we're assuming the UTxOs to be fully normalized.
