### ISSUE TITLE
Fix kind of HRec

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#385]
it should be `type HRec :: [(Symbol, Type)] -> Type`

**Comment by L-as** [comment]
I'm thinking maybe we don't want to change the kind but instead fix the constructor.

**Comment by L-as** [comment]
your idea is good

**Comment by TotallyNotChase** [comment]
I'm a bit confused here. I think `Labeled Symbol` wouldn't work as the environment here, since in the current use cases, `Labeled` is being treated as if it had the kind signature-
```hs
type Labeled :: Symbol -> Type -> Type
```
(though in reality, the current kind signature of `Labeled` is `forall k. k -> Type -> Type`)

That is, the first parameter of `Labeled` must be a type level symbol. `Labeled Symbol` wouldn't fit this description right? Since that'd mean `Labeled` has kind `Type -> Type -> Type`, and you can't actually specify `Labeled name` where `name :: Symbol`.

Anyway, the environment argument shouldn't actually take the `Symbol` literal I believe, since it's supposed to be different for each type in `as`.

I do think a lot of this `HRec` stuff and the machinery in `TryFrom` can be simplified via `sop-core` but it might be a bit involved.
